theme: jekyll-theme-architect
title: ML For Systems
google_analytics: true
site_description: Workshop on ML for Systems at NeurIPS 2025, TBA (will be December 6 or 7, 2025)
mini_site_description: Workshop on ML for Systems at NeurIPS '25, TBA (will be December 6 or 7, 2025)
workshop_name: neurips2025
mini_title: Current (2025)
